Repository jolocom/jolocom-lib, pull requests merged in 2018-10, with the labels that each got.

#205 Feature/#200 auth sig verification
  tests/data/interactionFlows/authentication.ts
  tests/data/interactionFlows/authenticationRequest.ts
  tests/data/interactionFlows/authenticationResponse.ts
  tests/identityWallet/identityWallet.test.ts
  tests/integration/index.ts
  tests/interactionFlows/authentication.test.ts
  tests/interactionFlows/authenticationRequest.test.ts
  tests/interactionFlows/authenticationResponse.test.ts
  tests/interactionFlows/authenticationResponsePayload.test.ts
  tests/interactionFlows/authenticatonPayload.test.ts
  tests/interactionFlows/authenticatonRequestPayload.test.ts
  ts/identityWallet/identityWallet.ts
  ts/interactionFlows/JSONWebToken.ts
  ts/interactionFlows/authentication/authentication.ts
  ts/interactionFlows/authentication/authenticationParser.ts
  ts/interactionFlows/authentication/authenticationPayload.ts
  ts/interactionFlows/authentication/types.ts
  ts/interactionFlows/authenticationRequest/authenticationRequest.ts
  ts/interactionFlows/authenticationRequest/authenticationRequestParser.ts
  ts/interactionFlows/authenticationRequest/authenticationRequestPayload.ts
  ts/interactionFlows/authenticationRequest/types.ts
  ts/interactionFlows/authenticationResponse/authenticationResponse.ts
  ts/interactionFlows/authenticationResponse/authenticationResponseParser.ts
  ts/interactionFlows/authenticationResponse/authenticationResponsePayload.ts
  ts/interactionFlows/authenticationResponse/types.ts
  ts/interactionFlows/types.ts
  ts/parse/parser.ts
Labels: finished, review

#204 Library documentation
  docs/gettingStarted.rst
  docs/index.rst
  docs/interactionFlows.rst
  docs/introduction.rst
  docs/publicProfile.rst
  docs/signedCredentials.rst
  docs/ssoSetUp.rst
  docs/usage.rst
  ts/interactionFlows/credentialResponse/credentialResponse.ts
  ts/interactionFlows/credentialResponse/credentialResponsePayload.ts
  ts/registries/jolocomRegistry.ts
Labels: finished

#212 [WIP] JWT parser refactor
  tests/interactionFlows/jsonWebToken.test.ts
  ts/interactionFlows/JSONWebTokenParser.ts
Labels: in progress

#214 Feature/#213 default context change
  tests/credential/credential.test.ts
  tests/data/credential/credential.ts
  tests/data/credential/signedCredential.ts
  tests/identityWallet/identityWallet.test.ts
  tests/interactionFlows/authentication.test.ts
  tests/interactionFlows/authenticatonPayload.test.ts
  tests/interactionFlows/credentialReceive.test.ts
  tests/interactionFlows/credentialReceivePayload.test.ts
  tests/interactionFlows/credentialRequestPayload.test.ts
  tests/interactionFlows/credentialResponse.test.ts
  tests/interactionFlows/credentialResponsePayload.test.ts
  tests/interactionFlows/jsonWebToken.test.ts
  ts/credentials/signedCredential/signedCredential.ts
  ts/identity/didDocument/index.ts
  ts/interactionFlows/JSONWebToken.ts
  ts/interactionFlows/JSONWebTokenParser.ts
  ts/interactionFlows/credentialResponse/credentialResponse.ts
  ts/linkedDataSignature/suites/ecdsaKoblitzSignature2016.ts
  ts/utils/contexts.ts
Labels: review

#216 Fix/iss jwt decode
  tests/integration/index.ts
  ts/interactionFlows/authentication/authenticationPayload.ts
  ts/interactionFlows/authentication/types.ts
  ts/interactionFlows/credentialRequest/credentialRequestPayload.ts
  ts/interactionFlows/credentialRequest/types.ts
  ts/interactionFlows/credentialResponse/credentialResponsePayload.ts
  ts/interactionFlows/credentialResponse/types.ts
  ts/interactionFlows/credentialsReceive/credentialsReceivePayload.ts
  ts/interactionFlows/credentialsReceive/types.ts
Labels: review

#226 Feature/#224 integration tests cred offer
  tests/data/interactionFlows/credentialOffer.ts
  tests/identityWallet/identityWallet.test.ts
  tests/integration/index.ts
  tests/interactionFlows/credentialOffer.test.ts
  tests/interactionFlows/credentialOfferRequestPayload.test.ts
  tests/interactionFlows/credentialOfferResponsePayload.test.ts
  tests/interactionFlows/credentialReceive.test.ts
  tests/interactionFlows/jsonWebToken.test.ts
  ts/identityWallet/identityWallet.ts
Labels: finished, review
