Repository jolocom/jolocom-lib, pull requests merged in 2018-11, with the labels that each got.

#231 Feature/#230 replay attack protection jwt
  tests/data/interactionTokens/jsonWebToken.data.ts
  tests/identityWallet/identityWallet.test.ts
  tests/interactionTokens/jsonWebToken.test.ts
  ts/identityWallet/identityWallet.ts
  ts/interactionTokens/JSONWebToken.ts
  ts/utils/helper.ts
Labels: finished, review

#235 Modifications to travis build script
  .travis.yml
Labels: review

#239 Feature/#232 validation method jwt
  tests/data/interactionTokens/jsonWebToken.data.ts
  tests/identityWallet/identityWallet.test.ts
  tests/identityWallet/validateJWT.test.ts
  tests/interactionTokens/jsonWebToken.test.ts
  ts/identityWallet/identityWallet.ts
  ts/interactionTokens/JSONWebToken.ts
  ts/interactionTokens/types.ts
  ts/ipfs/ipfs.ts
  ts/registries/types.ts
  ts/utils/helper.ts
Labels: finished, review

#240 Feature/#238 use accessors
  tests/credential/credential.test.ts
  tests/credential/signedCredential.test.ts
  tests/data/interactionTokens/jsonWebToken.data.ts
  tests/identity/didDocument.test.ts
  tests/identity/didDocumentSections.test.ts
  tests/identity/identity.test.ts
  tests/identityWallet/identityWallet.test.ts
  tests/integration/integration.ts
  tests/interactionTokens/authentication.test.ts
  tests/interactionTokens/credentialOffer.test.ts
  tests/interactionTokens/credentialReceive.test.ts
  tests/interactionTokens/credentialRequest.test.ts
  tests/interactionTokens/credentialResponse.test.ts
  tests/interactionTokens/jsonWebToken.test.ts
  tests/ipfs/ipfs.test.ts
  tests/jolocomRegistry/authenticate.test.ts
  tests/jolocomRegistry/resolve.test.ts
  tests/linkedDataSignatures/ecdsaKoblitzSignature2016.test.ts
  ts/credentials/credential/credential.ts
  ts/credentials/signedCredential/signedCredential.ts
  ts/ethereum/ethereum.ts
  ts/identity/didDocument/didDocument.ts
  ts/identity/didDocument/sections/authenticationSection.ts
  ts/identity/didDocument/sections/publicKeySection.ts
  ts/identity/didDocument/sections/serviceEndpointsSection.ts
  ts/identity/identity.ts
  ts/identityWallet/identityWallet.ts
  ts/interactionTokens/JSONWebToken.ts
  ts/interactionTokens/authentication.ts
  ts/interactionTokens/credentialOffer.ts
  ts/interactionTokens/credentialRequest.ts
  ts/interactionTokens/credentialResponse.ts
  ts/interactionTokens/credentialsReceive.ts
  ts/ipfs/ipfs.ts
  ts/linkedDataSignature/suites/ecdsaKoblitzSignature2016.ts
  ts/linkedDataSignature/types.ts
  ts/registries/jolocomRegistry.ts
  ts/utils/helper.ts
  ts/vaultedKeyProvider/softwareProvider.ts
Labels: finished

#244 Feature/#241 integration tests
  package.json
  tests/data/interactionTokens/authentication.data.ts
  tests/data/interactionTokens/credentialOffer.data.ts
  tests/identityWallet/identityWallet.test.ts
  tests/integration/authentication.integration.ts
  tests/integration/credentialOffer.integration.ts
  tests/integration/credentialShare.integration.ts
  tests/integration/identity.integration.ts
  tests/integration/integration.data.ts
  tests/interactionTokens/authentication.test.ts
  tests/interactionTokens/credentialOffer.test.ts
  ts/identityWallet/identityWallet.ts
  ts/interactionTokens/JSONWebToken.ts
  ts/interactionTokens/authentication.ts
  ts/interactionTokens/credentialOffer.ts
  ts/interactionTokens/interactionTokens.types.ts
Labels: finished

#253 Feature/#251 update documentation
  docs/Makefile
  docs/_themes/sphinx_rtd_theme
  docs/conf.py
  docs/gettingStarted.rst
  docs/index.rst
  docs/interactionFlows.rst
  docs/introduction.rst
  docs/make.bat
  docs/overview.jpg
  docs/protocolComponents.rst
  docs/publicProfile.rst
  docs/signedCredentials.rst
  docs/ssoSetUp.rst
Labels: finished, tech debt
