Repository jolocom/jolocom-lib, pull requests merged in 2018-06, with the labels that each got.

#78 Class and method for assembling credential response
  ts/credentialRequest/index.ts
  ts/credentialResponse/index.ts
  ts/credentialResponse/types.ts
  ts/index.ts
  ts/utils/credentials.ts
  ts/utils/general.ts
  ts/wallet/index.ts
Labels: finished, review

#80 Getter methods
  ts/credentialRequest/index.ts
Labels: finished, review

#82 added name credential type
  ts/credentials/credential/types.ts
  ts/index.ts
  ts/utils/contexts.ts
Labels: finished, review

#90 Feature/#89 static reviving methods
  ts/credentialRequest/index.ts
  ts/credentialResponse/index.ts
  ts/credentials/credential/index.ts
  ts/credentials/index.ts
  ts/credentials/verifiableCredential/index.ts
Labels: finished, new feature, review

#103 Static create method for credential
  ts/credentials/credential/index.ts
  ts/credentials/index.ts
Labels: finished, review

#106 Support for multiple claims per credential and tests
  package.json
  tests/credential/credential.test.ts
  tests/credential/signedCredential.test.ts
  tests/data/credential/credential.ts
  tests/data/credential/signedCredential.ts
  tests/identity.test.ts
  ts/credentials/credential/index.ts
  ts/credentials/credential/types.ts
  ts/credentials/index.ts
  ts/index.ts
  ts/utils/contexts.ts
Labels: finished, new feature, review

#105 Feature/#83 implement identity manager
  package.json
  tests/data/keys.ts
  tests/identityManager.test.ts
  ts/identity/index.ts
  ts/identityManager/identityManager.ts
  ts/utils/keyDerivation.ts
  yarn.lock
Labels: finished, review

#96 Feature/#86 implement registries
  package.json
  tests/data/identity.ts
  tests/data/keys.ts
  tests/data/registry.ts
  tests/jolocomRegistry.test.ts
  ts/ethereum/index.ts
  ts/ethereum/types.ts
  ts/identity/didDocument/index.ts
  ts/identity/didDocument/sections/types.ts
  ts/identity/didDocument/types.ts
  ts/identity/index.ts
  ts/identityWallet/identityWallet.ts
  ts/identityWallet/types.ts
  ts/ipfs/index.ts
  ts/ipfs/types.ts
  ts/registries/index.ts
  ts/registries/jolocomRegistry.ts
  ts/registries/types.ts
  ts/utils/crypto.ts
Labels: review

#101 Feature/#84 unsigned module implementation
  mocha.opts
  package.json
  tests/credentialResponse/signedCredentialResponse.test.ts
  ts/credentialRequest/credentialRequestParser.ts
  ts/credentialRequest/signedCredentialRequest/signedCredentialRequestParser.ts
  ts/credentialResponse/credentialResponseParser.ts
  ts/credentialResponse/signedCredentialResponse/signedCredentialResponseParser.ts
  ts/credentials/credential/credentialParser.ts
  ts/credentials/verifiableCredential/verifiableCredentialParser.ts
  ts/index.ts
  ts/parse/parser.ts
  yarn.lock
Labels: finished, in progress, review

#107 Feature/#85 insantiate module implementation
  ts/index.ts
Labels: finished, review

#95 IPLD methods & testing
  package.json
  tests/credential/signedCredential.test.ts
  tests/data/identity.ts
  tests/data/ipfs/ipfs.ts
  tests/data/keys.ts
  tests/identityManager.test.ts
  tests/ipfs/ipfs.test.ts
  tests/jolocomRegistry.test.ts
  ts/credentials/signedCredential/signedCredentialParser.ts
  ts/credentials/verifiableCredential/verifiableCredentialParser.ts
  ts/identity/index.ts
  ts/ipfs/index.ts
  ts/ipfs/types.ts
  ts/parse/parser.ts
  yarn.lock
Labels: new feature, review

#112 Feature/#99 public profile
  .vs/slnx.sqlite
  tests/credential/credential.test.ts
  tests/credentialRequest/signedCredentialRequest.test.ts
  tests/credentialResponse/signedCredentialResponse.test.ts
  tests/data/credential/credential.ts
  tests/data/identity.ts
  tests/data/ipfs.ts
  tests/ipfs/ipfs.test.ts
  tests/jolocomRegistry.test.ts
  ts/credentials/credential/index.ts
  ts/credentials/credential/types.ts
  ts/identity/didDocument/index.ts
  ts/identity/didDocument/sections/index.ts
  ts/identity/didDocument/sections/serviceEndpointsSection.ts
  ts/identity/didDocument/sections/types.ts
  ts/identity/didDocument/types.ts
  ts/identity/index.ts
  ts/index.ts
  ts/ipfs/index.ts
  ts/ipfs/types.ts
Labels: finished, review

#109 Identity wallet
  tests/credential/credential.test.ts
  tests/data/identity.ts
  tests/data/identityWallet.ts
  tests/data/keys.ts
  tests/identityWallet/identityWallet.test.ts
  tests/jolocomRegistry.test.ts
  ts/credentialRequest/signedCredentialRequest/signedCredentialRequest.ts
  ts/credentials/credential/credential.ts
  ts/credentials/credential/credentialParser.ts
  ts/credentials/credential/types.ts
  ts/credentials/index.ts
  ts/credentials/signedCredential/signedCredential.ts
  ts/credentials/signedCredential/signedCredentialParser.ts
  ts/credentials/signedCredential/types.ts
  ts/identityWallet/identityWallet.ts
  ts/identityWallet/types.ts
  ts/index.ts
  ts/registries/jolocomRegistry.ts
  ts/wallet/index.ts
  ts/wallet/types.ts
Labels: in progress

#116 Feature/#108 implement identity class
  tests/data/identity.ts
  tests/identity/identity.test.ts
  ts/identity/identity.ts
  ts/identity/types.ts
  ts/index.ts
Labels: finished, review

#122 Unified api
  ts/credentialRequest/credentialRequestParser.ts
  ts/credentialRequest/signedCredentialRequest/signedCredentialRequestParser.ts
  ts/credentialResponse/credentialResponseParser.ts
  ts/credentialResponse/signedCredentialResponse/signedCredentialResponseParser.ts
  ts/credentials/credential/credentialParser.ts
  ts/credentials/signedCredential/signedCredentialParser.ts
  ts/index.ts
  ts/parse/parser.ts
  ts/registries/index.ts
Labels: finished, review

#125 Feature/#124 adapt identity class
  .gitignore
  .vs/slnx.sqlite
  ts/credentialRequest/signedCredentialRequest/signedCredentialRequest.ts
  ts/credentialResponse/signedCredentialResponse/signedCredentialResponse.ts
  ts/credentials/signedCredential/signedCredential.ts
  ts/identity/didDocument/index.ts
  ts/identity/identity.ts
  ts/utils/jwt.ts
Labels: finished, review
