Repository jolocom/jolocom-lib, pull requests merged in 2019-04, with the labels that each got.

#289 Bump TS version, and type the parse object to ensure resulting declaration file is correct.
  package.json
  ts/parse/parse.ts
  yarn.lock
Labels: bug, finished

#292 264/revisit payments tests
  package.json
  tests/identityWallet/identityWallet.test.ts
  tests/identityWallet/validateJWT.test.ts
  tests/integration/identity.integration.ts
  tests/integration/payment.integration.ts
  tests/integration/provision.ts
  tests/jolocomRegistry/commit.test.ts
  tests/jolocomRegistry/jolocomRegistry.test.ts
  ts/contracts/contractsAdapter.ts
  ts/contracts/contractsGateway.ts
  ts/contracts/types.ts
  ts/identityWallet/identityWallet.ts
  ts/identityWallet/types.ts
  ts/interactionTokens/JSONWebToken.ts
  ts/interactionTokens/interactionTokens.types.ts
  ts/interactionTokens/paymentRequest.ts
  ts/interactionTokens/paymentResponse.ts
  ts/interactionTokens/types.ts
  ts/registries/jolocomRegistry.ts
  ts/registries/types.ts
  ts/utils/helper.ts
  yarn.lock
Labels: new feature

#301 Fix wrong key-types in public profile documentation
  docs/publicProfile.rst
Labels: documentation
